package com.example.demo.Model;

import java.util.Date;

public class Boke {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.id
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.image
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.title
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.description
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.time
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.name
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.lookcount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private Integer lookcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boke.likecount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    private Integer likecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.id
     *
     * @return the value of boke.id
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.id
     *
     * @param id the value for boke.id
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.image
     *
     * @return the value of boke.image
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.image
     *
     * @param image the value for boke.image
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.title
     *
     * @return the value of boke.title
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.title
     *
     * @param title the value for boke.title
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.description
     *
     * @return the value of boke.description
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.description
     *
     * @param description the value for boke.description
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.time
     *
     * @return the value of boke.time
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.time
     *
     * @param time the value for boke.time
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.name
     *
     * @return the value of boke.name
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.name
     *
     * @param name the value for boke.name
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.lookcount
     *
     * @return the value of boke.lookcount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public Integer getLookcount() {
        return lookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.lookcount
     *
     * @param lookcount the value for boke.lookcount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setLookcount(Integer lookcount) {
        this.lookcount = lookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boke.likecount
     *
     * @return the value of boke.likecount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boke.likecount
     *
     * @param likecount the value for boke.likecount
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }
}