package com.example.demo.Mapper;

import com.example.demo.Model.Boke;
import com.example.demo.Model.BokeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BokeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    long countByExample(BokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int deleteByExample(BokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int insert(Boke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int insertSelective(Boke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    List<Boke> selectByExampleWithRowbounds(BokeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    List<Boke> selectByExample(BokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    Boke selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") Boke record, @Param("example") BokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int updateByExample(@Param("record") Boke record, @Param("example") BokeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int updateByPrimaryKeySelective(Boke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boke
     *
     * @mbg.generated Tue Sep 21 11:59:17 CST 2021
     */
    int updateByPrimaryKey(Boke record);
}